#+ summary: List publications by year and title
#+ tags:
#+   - nasa-gesdisc-kg

PREFIX time: <http://www.w3.org/2006/time#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>
PREFIX gesdisc: <https://nasa-gesdisc.proto-okn.net/kg/schema/>
SELECT ?pub ?year ?title   {
  ?pub a gesdisc:Publication .
  ?pub time:year ?year .
  ?pub schema:title ?title .
}
LIMIT 100
