site_name: "okn.us"
theme:
  name: material
  custom_dir: material
  logo: assets/images/frink.png
  palette:
    scheme: default
    primary: custom
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate #puts the page anchor links on the left, instead of the right
    - navigation.indexes
copyright: "Powered by RENCI and Onai with <a href='https://www.nsf.gov/awardsearch/show-award/?AWD_ID=2535091' target='_blank'>NSF Award #2535091</a>"
extra:
  homepage: https://okn.us
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frink-okn/okn-registry
    - icon: okn-us/nsf
      link: https://www.nsf.gov/
      name: National Science Foundation
    - icon: material/lock
      link: https://okn.us/privacy
      name: okn.us Privacy Policy
    - icon: material/email
      link: mailto:contact@proto-okn.net
      name: Get in touch with okn.us via email
    - icon: material/email-box
      link: https://www.proto-okn.net/contact/
      name: Get in touch with okn.us via a form
    - icon: fontawesome/solid/play-circle
      link: https://www.proto-okn.net/presentations/
      name: See videos about okn.us
extra_css:
  - https://cdn.datatables.net/2.3.7/css/dataTables.dataTables.css
  - styles.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/2.3.7/js/dataTables.js
  - javascripts/header-button.js
  - javascripts/datatables.js
  - javascripts/mermaid.mjs
hooks:
  - hooks/kg_page_data.py
watch:
  - docs/registry/void
  - docs/registry/queries
  - hooks
  - material
plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
      arguments:
        maxTextSize: 500000
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - material/.icons
nav:
  - Graph Registry:
    - registry/index.md
    - Contribute to the Registry: registry/contribute.md
  - Querying Graphs:
    - query/index.md
    - How to Use the Query Tool: query/query-page.md
    - Sample Query Library: query/sample-query-library.md
    - Explore Graph Embeddings: https://apps.okn.us/embeddings/
    - Model Context Protocol Server: https://apps.okn.us/okn-mcp/mcp
  - Building Graphs:
      - Overview: book/index.md
      - Graph Construction Best Practices: book/best-practices.md
      - About External Identifiers: book/identifiers.md
      - Identifier Choices:
        - Biomedical: book/biomedical-identifiers.md
        - Environmental: book/environmental-identifiers.md
        - Geospatial: book/geospatial-identifiers.md
        - Institutions: book/institutions.md
        - Justice: book/justice.md
      - Ingesting Identifier Sources: book/new-id-sources.md
  - Uploading Graphs:
      - help/index.md
      - Setup a Repo in the Landing Zone: help/setup.md
      - Update Graphs in the OKN: help/update.md
      - Update Example Queries: help/update-queries.md
site_url: https://registry.okn.us

#     - Knowledge Graph (KG) Dataset Status: okn/kgstatus.md (add these links to the registry pages)
