site_name: "OKN: Fabric"
theme:
  name: material
  custom_dir: material
  logo: assets/images/frink.png
  palette:
    scheme: default
    primary: custom
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate #puts the page anchor links on the left, instead of the right
    - navigation.indexes
extra_css:
  - https://cdn.datatables.net/2.3.7/css/dataTables.dataTables.css
  - styles.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/2.3.7/js/dataTables.js
  - javascripts/header-button.js
  - javascripts/datatables.js
  - javascripts/mermaid.mjs
hooks:
  - hooks/kg_page_data.py
watch:
  - docs/registry/void
  - docs/registry/queries
  - hooks
  - material
plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
      arguments:
        maxTextSize: 500000
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - OKN Registry: 
    - registry/index.md
    - Contribute to the Registry: registry/contribute.md
  - Query the OKN:
    - query/index.md
    - Query Tool: query/query-page.md
    - Sample Query Library: query/sample-query-library.md
  - Building Graphs:
      - Overview: book/index.md
      - Graph Construction Best Practices: book/best-practices.md
      - About External Identifiers: book/identifiers.md
      - Identifier Choices:
        - Biomedical: book/biomedical-identifiers.md
        - Environmental: book/environmental-identifiers.md
        - Geospatial: book/geospatial-identifiers.md
        - Institutions: book/institutions.md
        - Justice: book/justice.md
      - Ingesting Identifier Sources: book/new-id-sources.md
  - Uploading Graphs: 
      - help/index.md
      - Setup a Repo in the Landing Zone: help/setup.md
      - Update Graphs in the OKN: help/update.md
      - Update Example Queries: help/update-queries.md
site_url: https://frink-okn.github.io
repo_url: https://github.com/frink-okn/frink-landing-zone/

#     - Knowledge Graph (KG) Dataset Status: okn/kgstatus.md (add these links to the registry pages)
