#+ summary: Find genes expressed in pancreas acinar cells and regulating cell-matrix adhesion
#+ tags:
#+   - pankgraph
#+   - ubergraph

PREFIX cl: <http://purl.obolibrary.org/obo/CL_>
PREFIX go: <http://purl.obolibrary.org/obo/GO_>
PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>

SELECT DISTINCT ?gene ?function {
    ?stmt1 rdf:subject ?gene ; rdf:predicate biolink:functional_association ; rdf:object ?function .
    ?stmt2 rdf:subject ?gene ; rdf:predicate biolink:expressed_in ; rdf:object cl:0002064 .
    ?function ro:0002211 go:0007160 .
}
