#+ summary: List software dependencies of versions of ffmpeg
#+ tags:
#+   - securechainkg

PREFIX schema: <http://schema.org/>
PREFIX sc: <https://w3id.org/secure-chain/>
SELECT ?package ?dependency {
  ?software schema:name "ffmpeg" .
  ?software sc:hasSoftwareVersion ?package .
  ?package sc:dependsOn ?dependency
}
LIMIT 100
