#+ summary: List vulnerabilities in versions of ffmpeg
#+ tags:
#+   - securechainkg

PREFIX schema: <http://schema.org/>
PREFIX sc: <https://w3id.org/secure-chain/>
SELECT ?vuln ?software {
  ?software schema:name "ffmpeg" .
  ?software sc:hasSoftwareVersion ?package .
  ?package sc:vulnerableTo ?vuln .
}
LIMIT 100
