#+ summary: Get all Soil Biological Samples and their corresponding attributes (date, lower and upper depth, expUnit, etc.)
#+ tags:
#+   - sockg
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sockg: <https://idir.uta.edu/sockg-ontology#>

SELECT DISTINCT ?expUnit ?date ?upperDepth ?lowerDepth ?label ?Value ?Unit WHERE {
    ?b a sockg:SoilBiologicalSample ;
        sockg:fromUnit ?e ;
        sockg:lowerDepth ?ld ;
        sockg:upperDepth ?ud ;
        dcterms:date ?date .

    ?e dcterms:identifier ?expUnit .
    ?ld qudt:numericValue ?lowerDepth .
    ?ud qudt:numericValue ?upperDepth .

    ?m sockg:of ?param ;
        qudt:quantityValue ?v .
    ?param a sockg:Parameter ;
            rdfs:label ?label .
    ?v qudt:numericValue ?Value ;
        qudt:hasUnit ?Unit .
}
ORDER BY ?expUnit ?date ?label
LIMIT 5