#+ summary: Retrieve all flowlines named 'Illinois River'
#+ tags:
#+   - hydrologykg

PREFIX hyf: <https://www.opengis.net/def/schema/hy_features/hyf/>
PREFIX nhdplusv2: <http://nhdplusv2.spatialai.org/v1/nhdplusv2#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

SELECT * WHERE {
  # Select flowlines and desired attributes
  ?flowline rdf:type hyf:HY_FlowPath ;
            schema:name ?name ;
            nhdplusv2:hasCOMID ?COMID ;
            nhdplusv2:hasFTYPE ?FTYPE .
  # Keep only flowlines with the desired name
  FILTER (?name = "Illinois River")
} ORDER BY ?COMID
